Pipeline

diff --git a/.github/workflows/smoke_test.yml b/.github/workflows/smoke_test.yml
--- a/.github/workflows/smoke_test.yml
+++ b/.github/workflows/smoke_test.yml
@@ -1,4 +1,4 @@
-name : Smoke Testing for Infra and Networking
+name : Smoke Testing For Infra and Networking
 
 on:
   workflow_call:
@@ -6,19 +6,58 @@ on:
 jobs:
   smoke:
     runs-on: ubuntu-latest
-
     steps:
       - uses: aws-actions/configure-aws-credentials@v4
         with:
           role-to-assume: arn:aws:iam::561516790720:role/github-action-deploy-role
           aws-region: us-east-1
-      - name: Upload smote_test.py on AWS
+      
+      - name: Upload smoke_test.py on AWS
         run: |
-          aws s3 cp smoke_test.py \
-          s3://561516790720-devops-scripts/smoke_test.py \
+          aws s3 cp scripts/smoke_test.py \
+          s3://720800607391-devops-scripts/smoke_test.py \
           --region us-east-1
-      - name: Run Smoke Test on Fleet 
+
+      - name: Run Smoke Test on Fleet
         id: smoke
-        run: | 
-        CMD_ID=$(aws ssm send-command \
-        --targets "key=") 
+        run: |
+          CMD_ID=$(aws ssm send-command \
+          --targets "Key=tag:App,Values=flask" \
+          --document-name "AWS-RunShellScript" \
+          --parameters '{"commands":[
+            "aws s3 cp s3://720800607391-devops-scripts/smoke_test.py /tmpr/smoke_test.py",
+            "python3 /tmpr/smoke_test.py",
+            "rm /tmpr/smoke_test.py"
+            ]}'\
+
+            --query 'Command.CommandId'\
+            --output text
+            --region us-east-1)
+
+          echo "cmd_id=$CMD_ID" >> $GITHUB_OUTPUT
+
+      - name: Show Results
+        run: |
+          sleep 30
+
+          aws ssm list-command-invocations \
+          --command-id "${{ steps.smoke.outputs.cmd_id }}" \
+          --details \
+          --region us-east-1
+          --output text
+
+          FAILED=$(aws ssm list-command-invocations \
+           --command-id "${{ steps.smoke.outputs.cmd_id }}" \
+           --query "length(CommandInvocations[?Status=='Failed'])" \
+           --output text \
+           --region us-east-1
+          )
+
+          [ "$FAILED" -gt 0 ] && \
+          echo "::error::Smoke Test  $FAILED instances" && \
+          exit 1
+
+          echo "Smoke Test Passed ✅"
+          
+
+      
