Pipeline

diff --git a/.github/workflows/test_fleet_health.yml b/.github/workflows/test_fleet_health.yml
--- a/.github/workflows/test_fleet_health.yml
+++ b/.github/workflows/test_fleet_health.yml
@@ -17,7 +17,8 @@ jobs:
           role-to-assume: arn:aws:iam::561516790720:role/github-action-deploy-role
           aws-region: us-east-1
 
-      - name: Print Private IPs
+      - name: Fleet Health check
+        id: health
         run: |
           CMD_ID=$(aws ssm send-command \
             --targets "Key=tag:App,Values=flask" \
@@ -29,13 +30,29 @@ jobs:
             "mysql --version 2>/dev/null || echo DOCKER NOT INSTALLED",
             "aws ssm get-parameters-by-path --path /application/banking --with-decryption --region us-east-1"
             ]}' \
-            --query 'Command.CommandId' --output text
-          )
+            --query 'Command.CommandId' --output text \
+            --region us-east-1)
+          echo "cmd_id"=$"CMD_ID" >> $GITHUB_OUTPUT
 
-          sleep 30
-
+      - name: show results
+        run: |
+          sleep 20
           aws ssm list-command-invocations \
-            --command-id "$CMD_ID" \
+            --command-id "${{steps.health.outputs.cmd_id}}" --details \
+            --region us-east-1
+            --query "CommandInvocations[*].{Instance:InstanceId,Status,IP:CommandPlugins[0].Output}" \
+            --output text
+          
+          FAILED=$(aws ssm list-command-invocations \
+            --command-id "${{steps.health.outputs.cmd_id}}" \
             --details \
-            --query "CommandInvocations[*].{Instance:InstanceId,IP:CommandPlugins[0].Output}" \
-            --output table
+            --query "length(CommandInvocations[?Status=='Failed'])" \
+            --output text \
+            --region us-east-1
+            )
+
+          [ "$FAILED" -gt 0 ] && \
+          echo "::error::Health Check Failed on $FAILED instances" && \
+          exit 1
+
+          echo "All Instance Healthy."
